# Generated by Django 3.1.4 on 2020-12-31 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dea.entitytype'),
        ),
        migrations.AlterField(
            model_name='accounttype_ext',
            name='description',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
